name: Continuous Integration & Delivery

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  # FIRST JOB: Verification
  build-and-test:
    name: 🧪 Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Lint check
        run: npm run lint

      - name: 🧪 Run unit tests
        run: npm test -- --watch=false --no-progress  
        #--pass-with-no-tests

  # SECOND JOB: Docker Build & Push
  deploy-docker:
    name: 🐳 Build & Push Docker
    needs: build-and-test # Only runs if build and tests succeed!
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop')
    runs-on: ubuntu-latest
    
    steps:
      - name: 🔍 Checkout code
        uses: actions/checkout@v4

      - name: 🔑 Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 🏗️ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🚀 Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Tag the image with 'latest' and the commit hash for traceability
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tdkportal-cokpit:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tdkportal-cokpit:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
      name: ☸️ Deploy to Kubernetes
      needs: build-docker # On attend que l'image soit sur le Hub
      runs-on: ubuntu-latest
      steps:
        - name: 📝 Checkout code
          uses: actions/checkout@v4

        - name: 🛠️ Setup kubectl
          uses: azure/k8s-set-context@v3
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.KUBE_CONFIG }}

        - name: 🚀 Apply Deployment & Restart
          run: |
            # On applique les changements du fichier YAML (namespace, ports, etc.)
            kubectl apply -f k8s/
            
            # Check
            kubectl get pods -n tdk-cockpit